permalink: /:path/:name/

collections:
  tutorial: 
    title: 'Tutorial'
    output: true
  concepts:
    title: 'Concepts'
    output: true

# Setup
title:               'argon.js documentation'
tagline:             'Documentation'
description:         'This site contains documentation for web developers using <a href="http://argonjs.io/design-aids" target="_blank">Design Aids</a> to add AR content to a web application.'
url:                 http://argonjs.io/design-aids/
baseurl:             '/'
#baseurl:             'http://argonjs.io/desing-aids/'

exclude: ['Rakefile', 'LICENSE.txt', 'CLA.md', 'CONTRIBUTING.md', 'README.md', "node_modules", "package.json"]

# About/contact
author:
  name:
  email:

# Local server settings
host: 0.0.0.0
port: 4000